<?php
 // module/Image/view/image/image/add.phtml:

 $title = 'Add Pics';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('image', array('action' => 'add')));
 $form->prepare();
 ?><div class="formBlock"><?php
 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('lien'));?></br><?php
 echo $this->formRow($form->get('idMembre'))?></br><?php
 echo $this->formSubmit($form->get('submit'));
 
 echo $this->form()->closeTag();
 ?></div><?php