<?php
 // module/Image/view/image/image/edit.phtml:

 $title = 'Edit Image';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'image',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 ?><div class="formBlock"><?php
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('title'));?></br><?php
 echo $this->formRow($form->get('artist'));?></br><?php
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?></div><?php