<?php
 // module/Album/view/image/image/index.phtml:

 use Zend\Authentication\AuthenticationService;
 use Zend\Session\Container;

 $title = 'Images';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $url = $this->url('image', array(
     'action' => 'index',
     'idMembre' => $this->idMembre,
 ));   
 ?>


 <?php foreach ($users as $user) : ?>
 
            <p>pseudo : <?php echo $user->username;?></p>
     
<?php endforeach; ?>
 
 
