<?php
 use Zend\Authentication\AuthenticationService;
 use Zend\Session\Container;

 $auth = new AuthenticationService();
 $logged = null;
 if ($auth->hasIdentity()){
    $session = new Container('user');
    $logged = $session->offsetGet('username');
    $userId =  $session->id;
 }
 
 $title =  $user->username.'\'s Pics';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $url = $this->url('image', array(
     'action' => 'membre',
     'id'     => $this->id,
 ));
 ?>
 
 <?php $i = 0;
      foreach ($images as $image) : ?>
        <div class="image">
        <img src="../../img/BanqueImage/<?php echo $this->escapeHtml($image->lien);?>" />
 <?php
            if($image->idMembre == $userId){
?>
                <a class="delete" href="<?php echo $this->url('image',
                    array('action'=>'delete', 'id' => $image->id));?>">X</a>
        </div>
      <?php }
            else{
                if($like != null){
                    if($like[$i] == 'FALSE'){
          ?>
                        <a class="like-delete like" href="<?php echo $this->url('like',
                                array('action'=>'delete', 'id' => $image->id));?>"><img src="../../img/pouce.jpg" /></a>
           <?php    }
                    else{
          ?>
                        <a class="like-add like" href="<?php echo $this->url('like',
                            array('action'=>'add', 'id' => $image->id));?>"><img src="../../img/pouce.jpg" /></a>
     <?php 
                    }
                }
                else{
     ?>
                    <a class="like-add like" href="<?php echo $this->url('like',
                            array('action'=>'add', 'id' => $image->id));?>"><img src="../../img/pouce.jpg" /></a>
     <?php
                }
            }
            $i++;
 endforeach; ?>